name: Test formulas

on:
  push:
    paths:
      - "Formula/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "Formula/**"
      - ".github/workflows/test.yml"

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Tap repository
        run: brew tap KiboMibo/tap
      - name: Install formula
        run: brew install KiboMibo/tap/sshmon
      - name: Test formula
        run: brew test KiboMibo/tap/sshmon
      - name: Verify executable
        run: test "$(sshmon --version)" = "sshmon 0.3.0"
